package dev.pvpbot.bot.trace;

public enum TraceEventType {
    MATCH_START,
    PERCEPTION_CAPTURED,
    PERCEPTION_MATURED,
    DECISION_UPDATED,
    AIM_PLAN_UPDATED,
    AIM_EXECUTION,
    MOVEMENT_PLAN_UPDATED,
    VERTICAL_ACTION,
    KNOCKBACK_STARTED,
    KNOCKBACK_ENDED,
    ATTACK_INTENT_CREATED,
    ATTACK_EXECUTED,
    CONFIRMED_HIT,
    MATCH_END,
    TRACE_SUMMARY
}
