package dev.pvpbot.database;

import dev.pvpbot.bot.profile.BotProfile;
import org.bukkit.plugin.java.JavaPlugin;
import java.nio.file.Path;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;

public final class DatabaseService implements AutoCloseable {
    public record Stats(int wins,int losses,int hits,int misses,double damage,int crits,int longestCombo) {}
    public record BotStats(int wins,int losses,int hits,int misses,double damage,int crits,int longestCombo) {}
    private final JavaPlugin plugin; private final String url; private final ExecutorService writer=Executors.newSingleThreadExecutor(Thread.ofPlatform().name("pvpbot-db").factory());
    public DatabaseService(JavaPlugin plugin){this.plugin=plugin;Path db=plugin.getDataFolder().toPath().resolve("pvpbot.db");url="jdbc:sqlite:"+db;initialize();}
    private void initialize(){try(Connection c=DriverManager.getConnection(url);Statement s=c.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("CREATE TABLE IF NOT EXISTS schema_version(version INTEGER NOT NULL)");s.execute("INSERT INTO schema_version(version) SELECT 1 WHERE NOT EXISTS(SELECT 1 FROM schema_version)");s.execute("CREATE TABLE IF NOT EXISTS player_stats(uuid TEXT PRIMARY KEY,wins INTEGER NOT NULL DEFAULT 0,losses INTEGER NOT NULL DEFAULT 0,hits INTEGER NOT NULL DEFAULT 0,misses INTEGER NOT NULL DEFAULT 0,damage REAL NOT NULL DEFAULT 0,crits INTEGER NOT NULL DEFAULT 0,longest_combo INTEGER NOT NULL DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS bot_stats(profile TEXT PRIMARY KEY,wins INTEGER NOT NULL DEFAULT 0,losses INTEGER NOT NULL DEFAULT 0,hits INTEGER NOT NULL DEFAULT 0,misses INTEGER NOT NULL DEFAULT 0,damage REAL NOT NULL DEFAULT 0,crits INTEGER NOT NULL DEFAULT 0,longest_combo INTEGER NOT NULL DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS matches(id TEXT PRIMARY KEY,player_uuid TEXT NOT NULL,profile TEXT NOT NULL,result TEXT NOT NULL,duration_ms INTEGER NOT NULL,player_hits INTEGER NOT NULL,player_misses INTEGER NOT NULL,bot_hits INTEGER NOT NULL,bot_misses INTEGER NOT NULL,player_damage REAL NOT NULL,bot_damage REAL NOT NULL,played_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");s.execute("CREATE TABLE IF NOT EXISTS custom_profiles(uuid TEXT PRIMARY KEY,data TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");plugin.getLogger().info("SQLite initialized; schema version 1");}catch(SQLException e){throw new IllegalStateException("Cannot initialize SQLite",e);}}
    public void record(UUID matchId,UUID player,String profile,boolean won,long duration,int playerHits,int botHits,int playerMisses,int botMisses,double playerDamage,double botDamage,int playerCrits,int botCrits,int playerCombo,int botCombo){writer.execute(()->{try(Connection c=DriverManager.getConnection(url)){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO matches(id,player_uuid,profile,result,duration_ms,player_hits,player_misses,bot_hits,bot_misses,player_damage,bot_damage) VALUES(?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,matchId.toString());p.setString(2,player.toString());p.setString(3,profile);p.setString(4,won?"WIN":"LOSS");p.setLong(5,duration);p.setInt(6,playerHits);p.setInt(7,playerMisses);p.setInt(8,botHits);p.setInt(9,botMisses);p.setDouble(10,playerDamage);p.setDouble(11,botDamage);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO player_stats(uuid,wins,losses,hits,misses,damage,crits,longest_combo) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET wins=wins+excluded.wins,losses=losses+excluded.losses,hits=hits+excluded.hits,misses=misses+excluded.misses,damage=damage+excluded.damage,crits=crits+excluded.crits,longest_combo=MAX(longest_combo,excluded.longest_combo)")){p.setString(1,player.toString());p.setInt(2,won?1:0);p.setInt(3,won?0:1);p.setInt(4,playerHits);p.setInt(5,playerMisses);p.setDouble(6,playerDamage);p.setInt(7,playerCrits);p.setInt(8,playerCombo);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO bot_stats(profile,wins,losses,hits,misses,damage,crits,longest_combo) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(profile) DO UPDATE SET wins=wins+excluded.wins,losses=losses+excluded.losses,hits=hits+excluded.hits,misses=misses+excluded.misses,damage=damage+excluded.damage,crits=crits+excluded.crits,longest_combo=MAX(longest_combo,excluded.longest_combo)")){p.setString(1,profile);p.setInt(2,won?0:1);p.setInt(3,won?1:0);p.setInt(4,botHits);p.setInt(5,botMisses);p.setDouble(6,botDamage);p.setInt(7,botCrits);p.setInt(8,botCombo);p.executeUpdate();}c.commit();}catch(SQLException e){plugin.getLogger().log(Level.SEVERE,"Failed to record match",e);}});}
    public Stats stats(UUID uuid){try(Connection c=DriverManager.getConnection(url);PreparedStatement p=c.prepareStatement("SELECT wins,losses,hits,misses,damage,crits,longest_combo FROM player_stats WHERE uuid=?")){p.setString(1,uuid.toString());try(ResultSet r=p.executeQuery()){return r.next()?new Stats(r.getInt(1),r.getInt(2),r.getInt(3),r.getInt(4),r.getDouble(5),r.getInt(6),r.getInt(7)):new Stats(0,0,0,0,0,0,0);}}catch(SQLException e){plugin.getLogger().log(Level.WARNING,"Failed to read stats",e);return new Stats(0,0,0,0,0,0,0);}}
    public BotStats botStats(String profile){try(Connection c=DriverManager.getConnection(url);PreparedStatement p=c.prepareStatement("SELECT wins,losses,hits,misses,damage,crits,longest_combo FROM bot_stats WHERE profile=?")){p.setString(1,profile.toUpperCase(Locale.ROOT));try(ResultSet r=p.executeQuery()){return r.next()?new BotStats(r.getInt(1),r.getInt(2),r.getInt(3),r.getInt(4),r.getDouble(5),r.getInt(6),r.getInt(7)):new BotStats(0,0,0,0,0,0,0);}}catch(SQLException e){plugin.getLogger().log(Level.WARNING,"Failed to read bot stats",e);return new BotStats(0,0,0,0,0,0,0);}}
    public void saveProfile(UUID uuid,BotProfile profile){String data=CustomProfileCodec.encode(profile);writer.execute(()->{try(Connection c=DriverManager.getConnection(url);PreparedStatement p=c.prepareStatement("INSERT INTO custom_profiles(uuid,data) VALUES(?,?) ON CONFLICT(uuid) DO UPDATE SET data=excluded.data,updated_at=CURRENT_TIMESTAMP")){p.setString(1,uuid.toString());p.setString(2,data);p.executeUpdate();}catch(SQLException e){plugin.getLogger().log(Level.WARNING,"Failed to save custom profile",e);}});}
    public Optional<BotProfile> loadProfile(UUID uuid){try(Connection c=DriverManager.getConnection(url);PreparedStatement p=c.prepareStatement("SELECT data FROM custom_profiles WHERE uuid=?")){p.setString(1,uuid.toString());try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();return Optional.of(CustomProfileCodec.decode(r.getString(1)));}}catch(SQLException|NumberFormatException e){plugin.getLogger().log(Level.WARNING,"Failed to load custom profile",e);return Optional.empty();}}
    public void close(){writer.shutdown();try{if(!writer.awaitTermination(5,TimeUnit.SECONDS))writer.shutdownNow();}catch(InterruptedException e){Thread.currentThread().interrupt();writer.shutdownNow();}}
}
